- name: set prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Create runner directory
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory
  become_user: ec2-user

- name: Download Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz
    dest: /home/ec2-user/github-runner
    remote_src: yes
  become_user: ec2-user

- name: Install Dependencies
  ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh

- name: Install Runner
  ansible.builtin.shell: ./config.sh remove --token BHDSEO727BK667LLYZRB6CLG4VZFQ; ./config.sh --unattended --replace --url https://github.com/a78devops --token {{secrets.GITHUB_RUNNER_TOKEN}}
  args:
    chdir: /home/ec2-user/github-runner
  become_user: ec2-user



