format_version: 10
pipelines:
  grafana:
    group: tools
    materials:
      git-683112d:
        git: https://github.com/a78devops/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
               - exec: {command: ansible-playbook, arguments: [ "-i", "grafana-internal.bdevops55.online,", "tools.yml", "-e", "tool_name=grafana", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}

