- name: install yum repo file
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: start vault service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: true

