- name: set prompt
  ansible.builtin.shell: set-prompt artifactory

- name: copy repo file
  ansible.builtin.template:
    src: jfrog.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo

- name: Install Jfrog
  ansible.builtin.dnf:
    name: jfrog-artifactory-oss
    state: installed
    disable_gpg_check: true




